# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tryptophantastic
email: heidih@gmail.com
description: >
  A place to muse about technical topics while invested in the Turing School full-stack web development program.

  A lightweight interpretation of a blog, playing with the Jekyll blog-aware site creator tool and GitHub pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "hhoopes.github.io" # the base hostname & protocol for your site
twitter_username: heidihoopes
github_username:  hhoopes

# Build settings
markdown: kramdown

permalink: pretty

paginate: 4

# Gems
gems: [jekyll-paginate]

#Plugins

# Only First P Plugin
only_first_p:
    show_read_more_link: true
    read_more_link_text: 'Read more'
